# Generated by Django 6.0.3 on 2026-08-08 09:57

import django.db.models.deletion
import django_mongodb_backend.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('OWNER', 'Pitch Owner'), ('PLAYER', 'Player')], default='PLAYER', max_length=20)),
                ('is_approved', models.BooleanField(default=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('profile_photo', models.ImageField(blank=True, help_text='Profile photo — updated via PATCH /accounts/me/photo/', null=True, upload_to='profile_photos/%Y/%m/')),
                ('password', models.CharField(blank=True, max_length=128)),
                ('active', models.BooleanField(default=True, help_text='check if user can access our system')),
                ('platform_admin', models.BooleanField(default=False, help_text='access everything bypass all thing')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.')),
                ('must_change_password', models.BooleanField(default=True, help_text='force password change for admin when owner create them')),
                ('failed_attempts', models.PositiveSmallIntegerField(default=0)),
                ('blocked_until', models.DateTimeField(blank=True, help_text='login blocked until - auto-expire', null=True)),
                ('last_login_at', models.DateTimeField(blank=True, help_text='last login to system', null=True)),
                ('last_login_ip', models.GenericIPAddressField(blank=True, help_text='Ip last successful login', null=True)),
                ('created_by_user_id', models.UUIDField(blank=True, help_text='who create this account only for admin', null=True)),
                ('last_failed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, help_text='soft delete data preserve, but user hidden from queries', null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
                'ordering': ['first_name'],
            },
        ),
        migrations.CreateModel(
            name='PhoneVerification',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('otp_hash', models.CharField(max_length=255)),
                ('purpose', models.CharField(choices=[('signup', 'Signup'), ('login', 'Login'), ('password_reset', 'Password Reset'), ('phone_change', 'Phone Change'), ('bid_confirm', 'Bid Confirm')], max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('attempts_locked_until', models.DateTimeField(blank=True, null=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('resend_count', models.PositiveSmallIntegerField(default=0)),
                ('resend_blocked_until', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phone_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Phone Verification',
                'verbose_name_plural': 'Phone Verifications',
                'db_table': 'phone_verifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_id', models.CharField(help_text='device fingerprint from flutter app', max_length=225)),
                ('device_name', models.CharField(blank=True, help_text='Human-readable device name. Example: Samsung s22', max_length=150, null=True)),
                ('admin_or_owner', models.BooleanField(default=False)),
                ('device_type', models.CharField(choices=[('android', 'Android'), ('ios', 'Ios'), ('mobile', 'Mobile'), ('tablet', 'Tablet'), ('desktop', 'Desktop'), ('web', 'Web')], default='mobile', help_text='mobile / desktop / website', max_length=20)),
                ('user_agent', models.TextField(blank=True, help_text='Full Http user-agent string', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Ip as session creation', null=True)),
                ('session_token_hash', models.CharField(help_text='SHA-256 hash of session token. Raw token sent to client once.', max_length=64, unique=True)),
                ('refresh_token_hash', models.CharField(help_text='SHA-256 hash of refresh token. Used for session rotation.', max_length=64, unique=True)),
                ('refresh_expires_at', models.DateTimeField(help_text='Refresh token hard expiry. After this user must login again.')),
                ('expires_at', models.DateTimeField(help_text='Hard session expiry. Session is invalid after this regardless of activity. Default: 7 days. Extended by refresh token (up to 30 days total).')),
                ('last_activity_at', models.DateTimeField(blank=True, help_text='Last confirmed activity. Updated max once per 5 min via Redis throttle. Used for "online now" detection and inactive session cleanup.', null=True)),
                ('is_revoked', models.BooleanField(default=False, help_text='True = session manually invalidated before natural expiry. Once True, never set back to False. Check revoke_reason for why it was revoked.')),
                ('revoke_reason', models.CharField(blank=True, choices=[('logout', 'User Logout'), ('password_change', 'Password Changed'), ('admin_action', 'Admin Action'), ('session_conflict', 'Session Conflict — New Device Login'), ('school_suspended', 'School Suspended'), ('org_suspended', 'Organization Suspended'), ('family_suspended', 'Family Suspended'), ('user_deleted', 'User Account Deleted'), ('family_deleted', 'Family Record Deleted'), ('phone_changed', 'Phone Number Changed'), ('security_action', 'Security Action'), ('pre_create_cleanup', 'Pre-Create Cleanup'), ('system', 'System Cleanup')], help_text='Why this session was revoked. Null while session is still active. Always set when is_revoked becomes True.', max_length=50, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, help_text='When this session was revoked. Null if still active.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(help_text='which user this session belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Session',
                'verbose_name_plural': 'User Sessions',
                'db_table': 'user_sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeviceToken',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fcm_token', models.TextField(help_text='Raw Firebase Cloud Messaging token sent by Flutter on login. FCM tokens can be long — use TextField not CharField.', unique=True)),
                ('device_id', models.CharField(db_index=True, help_text='Device fingerprint from Flutter. Same device_id used in UserSession. Links token to a specific physical device.', max_length=255)),
                ('device_name', models.CharField(blank=True, help_text='Human readable device name. Example: Samsung Galaxy S22.', max_length=150, null=True)),
                ('device_type', models.CharField(choices=[('android', 'Android'), ('ios', 'Ios'), ('mobile', 'Mobile'), ('tablet', 'Tablet'), ('desktop', 'Desktop'), ('web', 'Web')], default='mobile', help_text='mobile / desktop / web.', max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='False when session is revoked or FCM reports token as invalid. Inactive tokens are skipped by notification service.')),
                ('deactivated_at', models.DateTimeField(blank=True, help_text='When this token was deactivated.', null=True)),
                ('deactivated_reason', models.CharField(blank=True, help_text='Why token was deactivated. Examples: session_revoked, fcm_invalid, user_logout, replaced_by_new_token.', max_length=100, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, db_index=True, help_text='Last time a notification was successfully sent to this token. Null on brand new tokens — those are handled by orphan cleanup, not by the stale() queryset. Used by Celery to detect and deactivate genuinely stale tokens.', null=True)),
                ('user', models.ForeignKey(help_text='User this FCM token belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='device_tokens', to=settings.AUTH_USER_MODEL)),
                ('session', models.OneToOneField(blank=True, help_text='Session this token was registered with. SET_NULL (not CASCADE) is intentional — when a session is revoked the token becomes orphaned and is cleaned up by Celery rather than being hard-deleted immediately, giving in-flight notifications a chance to complete.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_token', to='accounts.usersession')),
            ],
            options={
                'verbose_name': 'Device Token',
                'verbose_name_plural': 'Device Tokens',
                'db_table': 'device_tokens',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='idx_device_token_user_active'), models.Index(fields=['device_id', 'is_active'], name='idx_device_token_device'), models.Index(fields=['last_used_at', 'is_active'], name='idx_device_token_stale')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('device_id',), name='unique_active_token_per_device')],
            },
        ),
    ]
