# Generated by Django 6.0.3 on 2026-08-23 17:43

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='user',
            index=models.Index(django.db.models.functions.text.Lower('username'), name='idx_user_username_lower'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(django.db.models.functions.text.Lower('first_name'), name='idx_user_first_name_lower'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(django.db.models.functions.text.Lower('last_name'), name='idx_user_last_name_lower'),
        ),
    ]
