# Generated by Django 6.0.3 on 2026-09-13 09:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_user_lower_search_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeenOnboardingTour',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tour_key', models.CharField(max_length=64)),
                ('seen_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seen_tours', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'seen_onboarding_tours',
                'constraints': [models.UniqueConstraint(fields=('user', 'tour_key'), name='unique_user_tour_key')],
            },
        ),
    ]
