# Generated by Django 6.0.3 on 2026-09-18 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_seenonboardingtour'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='seenonboardingtour',
            name='unique_user_tour_key',
        ),
        migrations.DeleteModel(
            name='SeenOnboardingTour',
        ),
    ]
