# Generated by Django 6.0.3 on 2026-03-04 14:55

import django.db.models.deletion
import django_mongodb_backend.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pitches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_type', models.CharField(choices=[('HOURLY', 'Hourly'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')], default='HOURLY', max_length=20)),
                ('start_dt', models.DateTimeField()),
                ('end_dt', models.DateTimeField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pitch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='pitches.pitch')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_dt', models.DateTimeField()),
                ('end_dt', models.DateTimeField()),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('BLOCKED', 'Blocked'), ('BOOKED', 'Booked')], default='AVAILABLE', max_length=20)),
                ('pitch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='pitches.pitch')),
            ],
            options={
                'indexes': [models.Index(fields=['pitch', 'start_dt'], name='bookings_sl_pitch_i_8c8edd_idx')],
            },
        ),
    ]
