# Generated by Django 6.0.3 on 2026-08-08 09:57

import django.db.models.deletion
import django_mongodb_backend.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pitches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_dt', models.DateTimeField()),
                ('end_dt', models.DateTimeField()),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('BLOCKED', 'Blocked'), ('BOOKED', 'Booked')], default='AVAILABLE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pitch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='pitches.pitch')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_slots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['start_dt'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_type', models.CharField(choices=[('HOURLY', 'Hourly'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')], default='HOURLY', max_length=20)),
                ('start_dt', models.DateTimeField()),
                ('end_dt', models.DateTimeField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('booking_code', models.CharField(blank=True, default='', max_length=12)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pitch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='pitches.pitch')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking', to='bookings.slot')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='slot',
            index=models.Index(fields=['pitch', 'start_dt'], name='bookings_sl_pitch_i_8c8edd_idx'),
        ),
        migrations.AddIndex(
            model_name='slot',
            index=models.Index(fields=['status'], name='bookings_sl_status_ad1968_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['pitch', 'start_dt'], name='bookings_bo_pitch_i_9987f6_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['player', 'created_at'], name='bookings_bo_player__5420d8_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status'], name='bookings_bo_status_233e96_idx'),
        ),
    ]
