# Generated by Django 6.0.3 on 2026-09-04 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='manual_booked_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='slot',
            name='manual_booked_phone',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
