# Generated by Django 6.0.3 on 2026-09-04 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_slot_manual_booked_name_slot_manual_booked_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='held_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
