# Generated by Django 6.0.3 on 2026-09-08 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_slot_held_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booked_for_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='booking',
            name='booked_for_phone',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='slot',
            name='manual_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
