# Generated by Django 6.0.3 on 2026-09-17 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_booked_for_name_booking_booked_for_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='manual_close_reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
