# Generated by Django 6.0.3 on 2026-10-04 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_solobookinghold'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='solobookinghold',
            name='bookings_so_player__86a627_idx',
        ),
        migrations.RemoveIndex(
            model_name='solobookinghold',
            name='bookings_so_status_dfe26c_idx',
        ),
        migrations.RemoveField(
            model_name='solobookinghold',
            name='pitch',
        ),
        migrations.RemoveField(
            model_name='solobookinghold',
            name='player',
        ),
    ]
