# Generated by Django 6.0.3 on 2026-10-04 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_remove_solobookinghold_bookings_so_player__86a627_idx_and_more'),
        ('payment', '0003_remove_paymenttransaction_payment_target_exactly_one_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SoloBookingHold',
        ),
    ]
