# Generated by Django 6.0.3 on 2026-10-04 08:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_delete_solobookinghold'),
        ('pitches', '0002_pitch_sport_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SoloBookingHold',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('booking_type', models.CharField(choices=[('HOURLY', 'Hourly'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')], default='HOURLY', max_length=20)),
                ('selections', models.JSONField(default=list)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('price_per_slot', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PAYMENT_PENDING', 'Payment Pending'), ('BOOKED', 'Booked'), ('UNAVAILABLE', 'Pitch Unavailable'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], default='PAYMENT_PENDING', max_length=20)),
                ('payment_expires_at', models.DateTimeField()),
                ('final_booking_code', models.CharField(blank=True, default='', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pitch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solo_booking_holds', to='pitches.pitch')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solo_booking_holds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['player', 'status'], name='bookings_so_player__86a627_idx'), models.Index(fields=['status', 'payment_expires_at'], name='bookings_so_status_dfe26c_idx')],
            },
        ),
    ]
