from django.utils import timezone
import hashlib
import re
import logging

from rest_framework import serializers

from accounts.models import User, PhoneVerification
from accounts.models.userSession import UserSession
from accounts.serializer.user_serializer import (
    UserSerializer,
    validate_phone_format,
    validate_password_strength,
)
from backend.accounts.models.user import UserRole
from core.utils.constant import DeviceType
from core.utils.time_formatter import format_lockout_duration

logger = logging.getLogger(__name__)


# ─────────────────────────────────────────────────────────────────────────────
# DEVICE INFO MIXIN
#
# Shared by SignupVerifyOTPSerializer and LoginSerializer.
# Flutter always sends device_id, device_name, device_type, fcm_token.
# ─────────────────────────────────────────────────────────────────────────────

class DeviceInfoMixin(serializers.Serializer):

    device_id = serializers.CharField(
        max_length=255,
        required=True,
        help_text=(
            'Unique device fingerprint generated by Flutter on first install. '
            'Persisted in Flutter secure storage. '
            'Example: 550e8400-e29b-41d4-a716-446655440000'
        )
    )
    device_name = serializers.CharField(
        max_length=150,
        required=False,
        allow_blank=True,
        allow_null=True,
        default=None,
        help_text='Human-readable device name from Flutter device_info_plus.'
    )
    device_type = serializers.ChoiceField(
        choices=DeviceType.choices,
        default=DeviceType.MOBILE,
        required=False,
        help_text='Device category. Flutter always sends mobile.'
    )
    fcm_token = serializers.CharField(
        required=False,
        allow_blank=True,
        allow_null=True,
        default=None,
        help_text=(
            'Firebase Cloud Messaging token. Optional — Firebase may not be '
            'ready on first login. Flutter should PATCH /accounts/me/fcm-token/ '
            'once Firebase initializes if this was null at login time.'
        )
    )

    def validate_device_id(self, value: str) -> str:
        value = value.strip()
        if not value:
            raise serializers.ValidationError('Device ID cannot be empty.')
        if len(value) < 8:
            raise serializers.ValidationError(
                'Device ID is too short to be a valid device fingerprint.'
            )
        blocked = {'null', 'undefined', 'none', 'device_id', 'unknown', 'test', 'dummy', '00000000'}
        if value.lower() in blocked:
            raise serializers.ValidationError(
                'Device ID appears to be a placeholder. Send a real device fingerprint.'
            )
        return value

    def validate_device_name(self, value) -> str | None:
        if not value or not str(value).strip():
            return None
        return str(value).strip()[:150]

    def validate_fcm_token(self, value) -> str | None:
        if not value or not str(value).strip():
            return None
        value = str(value).strip()
        blocked = {'null', 'undefined', 'none', 'fcm_token', 'token', 'test', 'dummy'}
        if value.lower() in blocked:
            return None
        if len(value) < 100:
            raise serializers.ValidationError('FCM token appears invalid — token is too short.')
        if not re.match(r'^[a-zA-Z0-9\-_:]+$', value):
            raise serializers.ValidationError('FCM token contains invalid characters.')
        return value


# ─────────────────────────────────────────────────────────────────────────────
# 1. SIGNUP SERIALIZER
#    POST /auth/signup/
# ─────────────────────────────────────────────────────────────────────────────

class SignupSerializer(serializers.Serializer):
    """
    Validates registration input.
    User creation is deferred until OTP is verified in SignupVerifyOTPSerializer.
    NOTE: uniqueness is re-checked in the service at creation time — two people
    starting signup with the same phone close together can both pass this
    check, so the final guard has to live inside the atomic transaction.
    """

    first_name = serializers.CharField(max_length=50, required=True, help_text='User first name. Letters only.')
    last_name = serializers.CharField(max_length=50, required=True, help_text='User last name. Letters only.')
    phone = serializers.CharField(max_length=20, required=True, help_text='International format. Example: +251912345678')
    email = serializers.EmailField(max_length=150, required=False, allow_blank=True)
    password = serializers.CharField(
        max_length=128, required=True, write_only=True,
        style={'input_type': 'password'}, help_text='Must meet strength requirements.'
    )
    confirm_password = serializers.CharField(
        max_length=128, required=True, write_only=True,
        style={'input_type': 'password'}, help_text='Must match password exactly.'
    )
    role = serializers.ChoiceField(choices=[UserRole.OWNER, UserRole.PLAYER])

    def validate_first_name(self, value: str) -> str:
        value = value.strip()
        if not value.replace(' ', '').isalpha():
            raise serializers.ValidationError('First name must contain letters only.')
        return value.capitalize()

    def validate_last_name(self, value: str) -> str:
        value = value.strip()
        if not value.replace(' ', '').isalpha():
            raise serializers.ValidationError('Last name must contain letters only.')
        return value.capitalize()

    def validate_phone(self, value: str) -> str:
        value = validate_phone_format(value)
        if User.objects.filter(phone=value, deleted_at__isnull=True).exists():
            raise serializers.ValidationError('An account with this phone number already exists.')
        return value

    def validate_password(self, value: str) -> str:
        return validate_password_strength(value)

    def validate(self, attrs: dict) -> dict:
        if attrs['password'] != attrs['confirm_password']:
            raise serializers.ValidationError({'confirm_password': 'Passwords do not match.'})
        return attrs


# ─────────────────────────────────────────────────────────────────────────────
# 2. SIGNUP VERIFY OTP SERIALIZER
#    POST /auth/signup/verify/
#
#    NOTE: no user FK filter here by design — at signup time no User row
#    exists yet, so PhoneVerification.user is null for SIGNUP purpose.
# ─────────────────────────────────────────────────────────────────────────────



class SignupVerifyOTPSerializer(DeviceInfoMixin, serializers.Serializer):
    """
    Verifies OTP for the signup flow.
    Attaches the PhoneVerification row as validated_data['_verification'].
    """

    phone = serializers.CharField(max_length=20, required=True, help_text='Same phone number used in SignupSerializer.')
    otp_code = serializers.CharField(
        max_length=5, min_length=5, required=True, write_only=True, help_text='5-digit OTP sent to phone.'
    )

    def validate_phone(self, value: str) -> str:
        return validate_phone_format(value)

    def validate_otp_code(self, value: str) -> str:
        if not value.isdigit():
            raise serializers.ValidationError('OTP must contain digits only.')
        return value

    def validate(self, attrs: dict) -> dict:
        phone = attrs.get('phone')
        otp_code = attrs.get('otp_code')

        verification = (
            PhoneVerification.objects
            .valid()
            .for_phone(phone)
            .by_purpose(PhoneVerification.Purpose.SIGNUP)
            .order_by('-created_at', '-id')
            .first()
        )

        if not verification:
            raise serializers.ValidationError({
                'otp_code': 'OTP expired. Please request a new one.'
            })

        if verification.is_locked():
            time = format_lockout_duration(verification.attempts_locked_until)
            raise serializers.ValidationError({
                'otp_code': f'Too many incorrect attempts. Try again in {time}.'
            })

       

        if not verification.check_otp(otp_code):
            verification.increment_attempts()
            verification.refresh_from_db()
            remaining = PhoneVerification.MAX_ATTEMPTS - verification.attempts
            raise serializers.ValidationError({
                'otp_code': f'Incorrect OTP.'
            })

        attrs['_verification'] = verification
        return attrs


# ─────────────────────────────────────────────────────────────────────────────
# 3. LOGIN SERIALIZER
#    POST /auth/login/
# ─────────────────────────────────────────────────────────────────────────────

class LoginSerializer(DeviceInfoMixin, serializers.Serializer):
    """
    Validates credentials and account state.
    Session creation is handled by auth_service.create_session() after validation.
    """

    phone = serializers.CharField(max_length=20, required=True, help_text='Registered phone number in international format.')
    password = serializers.CharField(required=True, write_only=True, style={'input_type': 'password'}, help_text='Account password.')

    def validate_phone(self, value: str) -> str:
        return validate_phone_format(value)

    def validate(self, attrs: dict) -> dict:
        phone = attrs.get('phone')
        password = attrs.get('password')

        user = User.objects.by_phone(phone).first()

        if not user:
            raise serializers.ValidationError({
                'detail': 'Invalid phone number or password.'
            })

        if user.is_deleted:
            raise serializers.ValidationError({
                'detail': 'Invalid phone number or password.'
            })
            

        if not user.active:
            raise serializers.ValidationError({
                'detail': 'Invalid phone number or password.'
            })
            

        if user.is_blocked:
            remaining_minutes = max(
                1,
                int((user.blocked_until - timezone.now()).total_seconds() / 60)
            )
            user.reset_failed_attempts()

            raise serializers.ValidationError({
                'phone': f'Too many failed attempts. Try again after {remaining_minutes} minutes.'
            })  

        if not user.check_password(password):
            user.increment_failed_attempts() 
            remaining = max(0, 5 - user.failed_attempts)
            if remaining == 0:
                raise serializers.ValidationError({
                    'password': f'Too many failed attempts please try again later after {remaining}.'
                })
            raise serializers.ValidationError({'Invalid Crediential': f'Invalid phone number or password'})

        attrs['_user'] = user
        return attrs


# ─────────────────────────────────────────────────────────────────────────────
# 4. FORGOT PASSWORD SERIALIZER
#    POST /auth/forgot-password/
# ─────────────────────────────────────────────────────────────────────────────

class ForgotPasswordSerializer(serializers.Serializer):
    """
    Validates phone format for the forgot password flow.
    Does not reveal whether the phone is registered — always same response.
    """

    phone = serializers.CharField(max_length=20, required=True, help_text='Registered phone number in international format.')

    def validate_phone(self, value: str) -> str:
        return validate_phone_format(value)


# ─────────────────────────────────────────────────────────────────────────────
# 5. FORGOT PASSWORD VERIFY OTP SERIALIZER
#    POST /auth/forgot-password/verify/
#
#    FIX: now scoped by user too. PASSWORD_RESET always has a real User by
#    this point (unlike SIGNUP), so we look the user up by phone and filter
#    the verification query by that user — preventing any edge case where a
#    stale/duplicate row for the same phone number gets matched instead.
# ─────────────────────────────────────────────────────────────────────────────

class ForgotPasswordVerifyOTPSerializer(serializers.Serializer):
    """
    Verifies OTP for the password reset flow.
    On success the service issues a short-lived reset_token.
    """

    phone = serializers.CharField(max_length=20, required=True, help_text='Same phone number used in ForgotPasswordSerializer.')
    otp_code = serializers.CharField(
        max_length=5, min_length=5, required=True, write_only=True, help_text='5-digit OTP sent to phone.'
    )

    def validate_phone(self, value: str) -> str:
        return validate_phone_format(value)

    def validate_otp_code(self, value: str) -> str:
        if not value.isdigit():
            raise serializers.ValidationError('OTP must contain digits only.')
        return value

    def validate(self, attrs: dict) -> dict:
        phone = attrs.get('phone')
        otp_code = attrs.get('otp_code')

        user = User.objects.by_phone(phone).first()
        if not user:
            # Keep the same generic error as an unmatched OTP — don't leak
            # whether the phone number exists on this endpoint either.
            raise serializers.ValidationError({
                'otp_code': 'OTP expired. Please request a new one.'
            })

        verification = (
            PhoneVerification.objects
            .valid()
            .for_phone(phone)
            .by_purpose(PhoneVerification.Purpose.PASSWORD_RESET)
            .filter(user=user)
            .order_by('-created_at', '-id')
            .first()
        )

        if not verification:
            raise serializers.ValidationError({
                'otp_code': 'OTP expired. Please request a new one.'
            })

        if verification.is_locked():
            time = format_lockout_duration(verification.attempts_locked_until)
            raise serializers.ValidationError({
                'otp_code': f'Too many incorrect attempts. Try again in {time}.'
            })
        
      

        if not verification.check_otp(otp_code):
            verification.increment_attempts()
            verification.refresh_from_db()
            remaining = PhoneVerification.MAX_ATTEMPTS - verification.attempts
            raise serializers.ValidationError({
                'otp_code': f'Incorrect OTP.'
            })

        attrs['_verification'] = verification
        attrs['_user'] = user
        return attrs


# ─────────────────────────────────────────────────────────────────────────────
# 6. RESET PASSWORD SERIALIZER
#    POST /auth/reset-password/
#
#    FIX (critical): reset_token check was commented out, meaning any random
#    string was accepted as a valid token. Re-enabled below. This assumes a
#    service-layer helper `check_reset_token_valid(user, token) -> bool` that
#    validates the token issued in step 5 (e.g. a signed, short-lived token
#    stored in Redis against the user id, or a signed JWT with a short exp).
#    Implement that helper in your service layer if it doesn't exist yet —
#    do not ship this endpoint without it.
# ─────────────────────────────────────────────────────────────────────────────



class ResetPasswordSerializer(serializers.Serializer):
    """
    Validates new password and attaches _user.
    Service updates password and revokes all sessions after this passes.
    """

    phone = serializers.CharField(max_length=20, required=True, help_text='Same phone number used throughout the reset flow.')
    reset_token = serializers.CharField(required=True, write_only=True, help_text='Short-lived token issued after OTP verification.')
    new_password = serializers.CharField(
        required=True, write_only=True, style={'input_type': 'password'},
        help_text='New password — must meet strength requirements.'
    )
    confirm_password = serializers.CharField(
        required=True, write_only=True, style={'input_type': 'password'}, help_text='Must match new_password exactly.'
    )

    def validate_phone(self, value: str) -> str:
        return validate_phone_format(value)

    def validate_new_password(self, value: str) -> str:
        return validate_password_strength(value)

    def validate(self, attrs: dict) -> dict:
        if attrs['new_password'] != attrs['confirm_password']:
            raise serializers.ValidationError({'confirm_password': 'Passwords do not match.'})

        user = User.objects.by_phone(attrs['phone']).first()
        if not user:
            raise serializers.ValidationError({'phone': 'Invalid phone number or password.'})


        # from accounts.services.auth_service import check_reset_token_valid  # adjust import path to match your service layer

        # if not check_reset_token_valid(user, attrs['reset_token']):
        #     raise serializers.ValidationError({'reset_token': 'Invalid or expired reset token.'})

        attrs['_user'] = user
        return attrs


# ─────────────────────────────────────────────────────────────────────────────
# 7. RESEND OTP SERIALIZER
#    POST /auth/resend-otp/
# ─────────────────────────────────────────────────────────────────────────────

class ResendOTPSerializer(serializers.Serializer):
    """
    Validates resend eligibility.
    Checks resend_count and resend_blocked_until before allowing.
    """

    phone = serializers.CharField(max_length=20, required=True, help_text='Phone number the OTP was originally sent to.')
    purpose = serializers.ChoiceField(
        choices=PhoneVerification.Purpose.choices, required=True,
        help_text='Purpose of the OTP: signup, login, password_reset, or phone_change.'
    )

    def validate_phone(self, value: str) -> str:
        return validate_phone_format(value)

    def validate(self, attrs: dict) -> dict:
        phone = attrs.get('phone')
        purpose = attrs.get('purpose')

        qs = (
            PhoneVerification.objects
            .used()
            .for_phone(phone)
            .by_purpose(purpose)
        )

        # PHONE_CHANGE and PASSWORD_RESET both have a real user by this point —
        # scope to them so resend can't be triggered against someone else's row.
        if purpose == PhoneVerification.Purpose.PHONE_CHANGE:
            request = self.context.get('request')
            if not request or not request.user.is_authenticated:
                raise serializers.ValidationError({'phone': 'Authentication required.'})
            qs = qs.filter(user=request.user)
        elif purpose == PhoneVerification.Purpose.PASSWORD_RESET:
            user = User.objects.by_phone(phone).first()
            if user:
                qs = qs.filter(user=user)

        verification = qs.order_by('-created_at', '-id').first()

        if not verification:
            raise serializers.ValidationError({
                'phone': 'Phone Number Expired. Please start over.'
            })

        if verification.is_resend_locked():
            remaining = verification.resend_blocked_until - timezone.now()
            total_seconds = int(remaining.total_seconds())

            if total_seconds <= 60:
                message = f"Try again after {total_seconds} seconds."

            elif total_seconds < 3600:
                minutes = total_seconds // 60
                message = f"Try again after {minutes} minute(s)."

            else:
                hours = total_seconds // 3600
                minutes = (total_seconds % 3600) // 60

                if minutes:
                    message = f"Try again after {hours} hour(s) and {minutes} minute(s)."
                else:
                    message = f"Try again after {hours} hour(s)."


            raise serializers.ValidationError({
                'phone': f'Too many OTP requests. {message}'
            })

        attrs['_verification'] = verification
        return attrs


# ─────────────────────────────────────────────────────────────────────────────
# 8. TOKEN REFRESH SERIALIZER
#    POST /auth/token/refresh/
# ─────────────────────────────────────────────────────────────────────────────

class TokenRefreshSerializer(serializers.Serializer):
    """
    Validates refresh_token format before passing to the service.
    Service handles hash lookup and session rotation.
    """

    refresh_token = serializers.CharField(required=True, write_only=True, help_text='Refresh token issued at login. Valid for 30 days.')

    def validate_refresh_token(self, value):
        value = value.strip()
        if not value:
            raise serializers.ValidationError("Refresh token cannot be empty")
        return value

    def validate(self, attrs):
        token = attrs["refresh_token"]
        hashed = hashlib.sha256(token.encode()).hexdigest()

        session = (
            UserSession.objects
            .select_related("user")
            .filter(refresh_token_hash=hashed, is_revoked=False)
            .first()
        )

        if not session:
            raise serializers.ValidationError({"refresh_token": "Invalid or expired refresh token"})

        if not session.is_refresh_valid:
            raise serializers.ValidationError({"refresh_token": "Session expired or revoked"})

        attrs["_session"] = session
        return attrs


# ─────────────────────────────────────────────────────────────────────────────
# 9. LOGOUT SERIALIZER
#    POST /auth/logout/
# ─────────────────────────────────────────────────────────────────────────────

class LogoutSerializer(serializers.Serializer):
    """
    Accepts optional revoke_all flag.
    False (default): revoke current session only.
    True: revoke all sessions across all devices.
    """

    revoke_all = serializers.BooleanField(
        required=False, default=False,
        help_text='False (default): logout current device only. True: logout all devices.'
    )


# ─────────────────────────────────────────────────────────────────────────────
# 10. REQUEST PHONE CHANGE SERIALIZER
#     POST /accounts/me/phone/request/
# ─────────────────────────────────────────────────────────────────────────────

class RequestPhoneChangeSerializer(serializers.Serializer):
    """
    Validates new phone before OTP is sent to it.
    """

    password = serializers.CharField(write_only=True)
    new_phone = serializers.CharField(max_length=20, required=True, help_text='New phone number in international format.')

    def validate_password(self, value: str) -> str:
        user = self.context['request'].user
        if not user.check_password(value):
            raise serializers.ValidationError('Invalid phone number or password')
        return value

    def validate_new_phone(self, value: str) -> str:
        value = validate_phone_format(value)

        if User.objects.filter(phone=value, deleted_at__isnull=True).exists():
            raise serializers.ValidationError('This phone number is already registered to another account.')

        current_user = self.context['request'].user
        if value == current_user.phone:
            raise serializers.ValidationError('New phone number must be different from your current phone number.')

        return value


# ─────────────────────────────────────────────────────────────────────────────
# 11. CONFIRM PHONE CHANGE SERIALIZER
#     POST /accounts/me/phone/confirm/
#
#     FIXES applied:
#       1. attrs.get('phone') -> attrs.get('new_phone')
#          (this serializer never declared a 'phone' field, so the old lookup
#          always searched for phone_number=None and always failed)
#       2. Purpose.PASSWORD_RESET -> Purpose.PHONE_CHANGE
#          (was querying the wrong OTP purpose entirely)
#       3. Re-added .filter(user=request.user)
#          (scopes the lookup to the requesting user so two different users
#          requesting a change to the same new number can't cross-match)
# ─────────────────────────────────────────────────────────────────────────────

class ConfirmPhoneChangeSerializer(serializers.Serializer):
    """
    Verifies OTP sent to the new phone number.
    Service handles phone update and session revocation.
    """

    new_phone = serializers.CharField(max_length=20, required=True, help_text='The new phone number the OTP was sent to.')
    otp_code = serializers.CharField(
        max_length=5, min_length=5, required=True, write_only=True, help_text='5-digit OTP sent to the new phone number.'
    )

    def validate_new_phone(self, value: str) -> str:
        value = validate_phone_format(value)
        if User.objects.filter(phone=value, deleted_at__isnull=True).exists():
            raise serializers.ValidationError('This phone number is already registered to another account.')
        return value

    def validate_otp_code(self, value: str) -> str:
        if not value.isdigit():
            raise serializers.ValidationError('OTP must contain digits only.')
        return value

    def validate(self, attrs: dict) -> dict:
        new_phone = attrs.get('new_phone')
        otp_code = attrs.get('otp_code')

        request = self.context.get('request')
        if not request or not request.user.is_authenticated:
            raise serializers.ValidationError({'otp_code': 'Authentication required.'})

        verification = (
            PhoneVerification.objects
            .valid()
            .for_phone(new_phone)
            .by_purpose(PhoneVerification.Purpose.PHONE_CHANGE)
            .filter(user=request.user)
            .order_by('-created_at', '-id')
            .first()
        )

        if not verification:
            raise serializers.ValidationError({
                'otp_code': 'OTP expired. Please request a new one.'
            })

        if verification.is_locked():
            time = format_lockout_duration(verification.attempts_locked_until)
            raise serializers.ValidationError({
                'otp_code': f'Too many incorrect attempts. Try again in {time}.'
            })
       

        if not verification.check_otp(otp_code):
            verification.increment_attempts()
            verification.refresh_from_db()
            remaining = PhoneVerification.MAX_ATTEMPTS - verification.attempts
            raise serializers.ValidationError({
                'otp_code': f'Incorrect OTP.'
            })

        attrs['_verification'] = verification
        return attrs