# Generated by Django 6.0.3 on 2026-08-25 19:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('team', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('audio', 'Audio'), ('system', 'System')], default='text', max_length=10)),
                ('content', models.TextField(blank=True, max_length=4000)),
                ('audio_file', models.FileField(blank=True, help_text='Stored on your MEDIA storage backend. Do NOT expose this via a public MEDIA_URL for chat — private team audio must be served through an authenticated endpoint that checks the requester is an active member of `team`, not a raw static file path anyone with the URL could hit.', null=True, upload_to='chat/audio/%Y/%m/')),
                ('audio_duration_seconds', models.PositiveSmallIntegerField(blank=True, help_text='Reported by the client at record time (from MediaRecorder timing), not re-derived server-side.', null=True)),
                ('audio_mime_type', models.CharField(blank=True, help_text="e.g. 'audio/webm', 'audio/ogg' — needed so playback knows the container format; varies by recording browser/device.", max_length=50)),
                ('audio_file_size_bytes', models.PositiveIntegerField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(blank=True, help_text="Nullable via SET_NULL rather than CASCADE: if a user account is ever hard-deleted, chat history should survive (shown as 'Deleted user'), not disappear. In normal operation this stays populated — your User model soft-deletes (deleted_at), it doesn't hard-delete rows.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_chat_messages', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='team.team')),
            ],
            options={
                'verbose_name': 'Team Chat Message',
                'verbose_name_plural': 'Team Chat Messages',
                'db_table': 'chat_team_chat_message',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['team', '-created_at'], name='idx_chat_team_created')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('message_type', 'audio'), _negated=True), models.Q(('audio_file', ''), _negated=True), _connector='OR'), name='chat_message_audio_requires_file'), models.CheckConstraint(condition=models.Q(('message_type', 'audio'), models.Q(('content', ''), _negated=True), _connector='OR'), name='chat_message_text_requires_content')],
            },
        ),
    ]
