# Generated by Django 6.0.3 on 2026-08-26 08:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        ('team', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamChatReadState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('last_read_at', models.DateTimeField(blank=True, help_text="NULL means this user has never opened this team's chat — everything in it is unread.", null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_read_states', to='team.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_read_states', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Team Chat Read State',
                'verbose_name_plural': 'Team Chat Read States',
                'db_table': 'chat_team_chat_read_state',
                'indexes': [models.Index(fields=['user'], name='chat_team_c_user_id_e435c0_idx')],
                'constraints': [models.UniqueConstraint(fields=('team', 'user'), name='uniq_read_state_per_team_user')],
            },
        ),
    ]
