# Generated by Django 6.0.3 on 2026-08-28 09:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_teamchatreadstate'),
        ('team', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='teamchatmessage',
            name='chat_message_audio_requires_file',
        ),
        migrations.RemoveConstraint(
            model_name='teamchatmessage',
            name='chat_message_text_requires_content',
        ),
        migrations.AddField(
            model_name='teamchatmessage',
            name='image_file',
            field=models.ImageField(blank=True, help_text='Stored on your MEDIA storage backend. Like audio, never expose via a public MEDIA_URL — served through an authenticated endpoint the same way audio is.', null=True, upload_to='chat/images/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='teamchatmessage',
            name='image_file_size_bytes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teamchatmessage',
            name='image_mime_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='teamchatmessage',
            name='message_type',
            field=models.CharField(choices=[('TEXT', 'Text'), ('AUDIO', 'Audio'), ('IMAGE', 'Image'), ('SYSTEM', 'System')], default='TEXT', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='teamchatmessage',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('message_type', 'AUDIO'), _negated=True), models.Q(('audio_file', ''), _negated=True), _connector='OR'), name='chat_message_audio_requires_file'),
        ),
        migrations.AddConstraint(
            model_name='teamchatmessage',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('message_type', 'TEXT'), _negated=True), models.Q(('content', ''), _negated=True), _connector='OR'), name='chat_message_text_requires_content'),
        ),
        migrations.AddConstraint(
            model_name='teamchatmessage',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('message_type', 'IMAGE'), _negated=True), models.Q(('image_file', ''), _negated=True), _connector='OR'), name='chat_message_image_requires_file'),
        ),
    ]
