# Generated by Django 6.0.3 on 2026-08-12 08:08

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pitch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('address', models.CharField(blank=True, default='', max_length=255)),
                ('min_hours', models.PositiveIntegerField(default=1)),
                ('allow_hourly', models.BooleanField(default=True)),
                ('allow_weekly', models.BooleanField(default=False)),
                ('allow_monthly', models.BooleanField(default=False)),
                ('hourly_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('weekly_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('monthly_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('opening_time', models.TimeField(default=datetime.time(8, 0))),
                ('closing_time', models.TimeField(default=datetime.time(22, 0))),
                ('has_dressing_room', models.BooleanField(default=False)),
                ('has_showers', models.BooleanField(default=False)),
                ('has_parking', models.BooleanField(default=False)),
                ('has_lighting', models.BooleanField(default=False)),
                ('other_services', models.CharField(blank=True, default='', help_text='Comma-separated services (e.g., referee, water, ball rental).', max_length=255)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PitchImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='pitch_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pitch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='pitches.pitch')),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tenant', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='pitch',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pitches', to='pitches.tenant'),
        ),
    ]
