# Generated by Django 6.0.3 on 2026-08-26 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pitches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitch',
            name='sport_type',
            field=models.CharField(choices=[('FOOTBALL', 'Football'), ('BASKETBALL', 'Basketball')], default='FOOTBALL', max_length=20),
        ),
    ]
