# Generated by Django 6.0.3 on 2026-03-06 13:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pitches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitch',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pitch',
            name='has_dressing_room',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pitch',
            name='has_lighting',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pitch',
            name='has_parking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pitch',
            name='has_showers',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pitch',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pitch',
            name='other_services',
            field=models.CharField(blank=True, default='', help_text='Comma-separated services (e.g., referee, water, ball rental).', max_length=255),
        ),
        migrations.AddField(
            model_name='tenant',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tenant',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
