# Generated by Django 6.0.3 on 2026-09-04 11:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('team', '0002_alter_team_sport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamBookingRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pitch_id', models.CharField(max_length=64)),
                ('pitch_name', models.CharField(max_length=200)),
                ('booking_type', models.CharField(max_length=10)),
                ('selections', models.JSONField(default=list)),
                ('notes', models.TextField(blank=True, default='')),
                ('price_per_member', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('member_count_at_creation', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending', max_length=12)),
                ('expires_at', models.DateTimeField()),
                ('summary_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_booking_requests_created', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_requests', to='team.team')),
            ],
            options={
                'db_table': 'team_booking_request',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeamBookingConfirmation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('declined', 'Declined')], default='pending', max_length=10)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_booking_confirmations', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmations', to='team_booking.teambookingrequest')),
            ],
            options={
                'db_table': 'team_booking_confirmation',
            },
        ),
        migrations.AddIndex(
            model_name='teambookingrequest',
            index=models.Index(fields=['team', 'status'], name='team_bookin_team_id_6b1d86_idx'),
        ),
        migrations.AddIndex(
            model_name='teambookingrequest',
            index=models.Index(fields=['status', 'expires_at'], name='team_bookin_status_e289eb_idx'),
        ),
        migrations.AddIndex(
            model_name='teambookingconfirmation',
            index=models.Index(fields=['member', 'status'], name='team_bookin_member__3a2838_idx'),
        ),
        migrations.AddIndex(
            model_name='teambookingconfirmation',
            index=models.Index(fields=['request', 'status'], name='team_bookin_request_9f6369_idx'),
        ),
        migrations.AddConstraint(
            model_name='teambookingconfirmation',
            constraint=models.UniqueConstraint(fields=('request', 'member'), name='uniq_confirmation_per_request_member'),
        ),
    ]
