# Generated by Django 6.0.3 on 2026-09-04 12:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_booking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='teambookingrequest',
            name='final_booking_code',
            field=models.CharField(blank=True, default='', max_length=12),
        ),
        migrations.AddField(
            model_name='teambookingrequest',
            name='owner_action_taken',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teambookingrequest',
            name='payment_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teambookingrequest',
            name='payment_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teambookingrequest',
            name='payment_timeout_needs_owner_action',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='teambookingrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('expired', 'Expired'), ('payment_pending', 'Payment Pending'), ('booked', 'Booked'), ('unavailable', 'Pitch Unavailable'), ('cancelled', 'Cancelled')], default='pending', max_length=16),
        ),
        migrations.CreateModel(
            name='TeamBookingPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_owner', models.BooleanField(default=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('covered_by_owner', 'Covered by Owner')], default='pending', max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_booking_payments', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='team_booking.teambookingrequest')),
            ],
            options={
                'db_table': 'team_booking_payment',
                'indexes': [models.Index(fields=['request', 'status'], name='team_bookin_request_a9a3f7_idx'), models.Index(fields=['payer', 'status'], name='team_bookin_payer_i_9fcc30_idx')],
                'constraints': [models.UniqueConstraint(fields=('request', 'payer'), name='uniq_payment_per_request_payer')],
            },
        ),
    ]
