# Generated by Django 6.0.3 on 2026-09-05 07:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_booking', '0002_teambookingrequest_final_booking_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='teambookingpayment',
            name='uniq_payment_per_request_payer',
        ),
        migrations.AddField(
            model_name='teambookingpayment',
            name='round',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='teambookingrequest',
            name='payment_round',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='teambookingpayment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('covered_by_owner', 'Covered by Owner'), ('excluded', 'Excluded')], default='pending', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='teambookingpayment',
            constraint=models.UniqueConstraint(fields=('request', 'payer', 'round'), name='uniq_payment_per_request_payer_round'),
        ),
    ]
