# Generated by Django 6.0.3 on 2026-09-07 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0002_remove_match_match_fields_match_type_and_more'),
        ('team_booking', '0003_remove_teambookingpayment_uniq_payment_per_request_payer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teambookingrequest',
            name='open_slot_match',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_booking_request', to='match.match'),
        ),
        migrations.AlterField(
            model_name='teambookingrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('expired', 'Expired'), ('awaiting_open_slots', 'Awaiting Open Slots'), ('payment_pending', 'Payment Pending'), ('booked', 'Booked'), ('unavailable', 'Pitch Unavailable'), ('cancelled', 'Cancelled')], default='pending', max_length=24),
        ),
    ]
