# Generated by Django 6.0.3 on 2026-09-08 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_booking', '0004_teambookingrequest_open_slot_match_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teambookingrequest',
            name='booked_popup_shown',
            field=models.BooleanField(default=False),
        ),
    ]
