# Generated by Django 6.0.3 on 2026-09-04 11:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('team_invitation_received', 'Team Invitation Received'), ('team_invitation_accepted', 'Invitation Accepted'), ('team_invitation_declined', 'Invitation Declined'), ('team_join_request_received', 'New Join Request'), ('team_join_request_approved', 'Join Request Approved'), ('team_join_request_rejected', 'Join Request Rejected'), ('team_role_changed', 'Your Role Changed'), ('team_member_removed', 'Removed From Team'), ('team_ownership_transferred', 'You Are Now Team Owner'), ('chat_message_received', 'New Message'), ('match_challenge_accepted', 'Challenge Accepted'), ('match_player_joined', 'Player Joined Your Match'), ('match_confirmed', 'Match Confirmed'), ('match_cancelled', 'Match Cancelled'), ('match_reminder', 'Upcoming Match Reminder'), ('team_booking_request_received', 'Team Booking Request'), ('team_booking_member_responded', 'Member Responded'), ('team_booking_summary', 'Booking Response Summary'), ('system', 'System')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('push_sent', models.BooleanField(default=False)),
                ('push_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notification_notification',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read', 'created_at'], name='notificatio_recipie_a71530_idx'), models.Index(fields=['notification_type'], name='notificatio_notific_a5f01d_idx')],
            },
        ),
    ]
