# Generated by Django 6.0.3 on 2026-09-08 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('team_invitation_received', 'Team Invitation Received'), ('team_invitation_accepted', 'Invitation Accepted'), ('team_invitation_declined', 'Invitation Declined'), ('team_join_request_received', 'New Join Request'), ('team_join_request_approved', 'Join Request Approved'), ('team_join_request_rejected', 'Join Request Rejected'), ('team_role_changed', 'Your Role Changed'), ('team_member_removed', 'Removed From Team'), ('team_ownership_transferred', 'You Are Now Team Owner'), ('chat_message_received', 'New Message'), ('match_challenge_accepted', 'Challenge Accepted'), ('match_player_joined', 'Player Joined Your Match'), ('match_confirmed', 'Match Confirmed'), ('match_cancelled', 'Match Cancelled'), ('match_reminder', 'Upcoming Match Reminder'), ('team_booking_request_received', 'Team Booking Request'), ('team_booking_member_responded', 'Member Responded'), ('team_booking_summary', 'Booking Response Summary'), ('team_booking_payment_request', 'Payment Requested'), ('team_booking_payment_received', 'Payment Received'), ('team_booking_pitch_booked', 'Pitch Booked'), ('team_booking_pitch_unavailable', 'Pitch Unavailable'), ('team_booking_open_slot_joined', 'Player Joined Open Slot'), ('system', 'System')], max_length=30),
        ),
    ]
