# Generated by Django 6.0.3 on 2026-09-01 10:49

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pitches', '0002_pitch_sport_type'),
        ('team', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('match_type', models.CharField(choices=[('team_vs_team', 'Team vs Team'), ('open_slots', 'Open Slots')], max_length=15)),
                ('status', models.CharField(choices=[('open', 'Open'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='open', max_length=10)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('description', models.TextField(blank=True)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('slots_needed', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('price_per_slot', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matches_created_by_me', to=settings.AUTH_USER_MODEL)),
                ('creator_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_matches', to='team.team')),
                ('opponent_team', models.ForeignKey(blank=True, help_text='TEAM_VS_TEAM only. NULL until another team accepts.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='challenged_matches', to='team.team')),
                ('pitch', models.ForeignKey(help_text='Location is derived through this FK, not stored on Match directly.', on_delete=django.db.models.deletion.PROTECT, related_name='matches', to='pitches.pitch')),
            ],
            options={
                'db_table': 'match_match',
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='MatchParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('reserved', 'Reserved'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='reserved', max_length=10)),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=10)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('status_changed_at', models.DateTimeField(blank=True, null=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='match.match')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'match_match_participant',
                'ordering': ['joined_at'],
            },
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['status', 'start_time'], name='match_match_status_87e36b_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['match_type', 'status'], name='match_match_match_t_d3cae3_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['creator_team', 'status'], name='match_match_creator_97078e_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['opponent_team', 'status'], name='match_match_opponen_ad00cc_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['pitch', 'start_time'], name='match_match_pitch_i_89dd88_idx'),
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('match_type', 'team_vs_team'), ('price_per_slot__isnull', True), ('slots_needed__isnull', True), ('total_price__isnull', False)), models.Q(('match_type', 'open_slots'), ('price_per_slot__isnull', False), ('slots_needed__isnull', False), ('total_price__isnull', True)), _connector='OR'), name='match_fields_match_type'),
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.CheckConstraint(condition=models.Q(('opponent_team', models.F('creator_team')), _negated=True), name='match_opponent_not_self'),
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='match_end_after_start'),
        ),
        migrations.AddIndex(
            model_name='matchparticipant',
            index=models.Index(fields=['match', 'status'], name='match_match_match_i_66090f_idx'),
        ),
        migrations.AddIndex(
            model_name='matchparticipant',
            index=models.Index(fields=['user', 'status'], name='match_match_user_id_d322b4_idx'),
        ),
        migrations.AddConstraint(
            model_name='matchparticipant',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['reserved', 'confirmed'])), fields=('match', 'user'), name='uniq_active_participant_per_match_user'),
        ),
    ]
