# Generated by Django 6.0.3 on 2026-09-07 07:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='match',
            name='match_fields_match_type',
        ),
        migrations.RemoveConstraint(
            model_name='match',
            name='match_opponent_not_self',
        ),
        migrations.RemoveIndex(
            model_name='match',
            name='match_match_match_t_d3cae3_idx',
        ),
        migrations.RemoveIndex(
            model_name='match',
            name='match_match_opponen_ad00cc_idx',
        ),
        migrations.AlterField(
            model_name='match',
            name='price_per_slot',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='match',
            name='slots_needed',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='match',
            name='match_type',
        ),
        migrations.RemoveField(
            model_name='match',
            name='opponent_team',
        ),
        migrations.RemoveField(
            model_name='match',
            name='total_price',
        ),
    ]
