
import {
  type TeamSummary,
  type UpcomingMatch,
  type TournamentPreview,
  type AppNotification,
  type MatchFull,
  type PitchResult,
  type PublicTeamResult,
  type TournamentFull,
  type UserProfile,
} from "./types";

// TODO: replace every export in this file with real API calls
// (e.g. GET /me/teams, GET /me/matches/upcoming, /tournaments/relevant, /me/notifications)

export const mockTeams: TeamSummary[] = [
  {
    id: "bole-united",
    name: "Bole United",
    logo: null,
    sport: "Football",
    location: "Bole, Addis Ababa",
    activeMembers: 14,
    capacity: 18,
    role: "OWNER",
  },
  {
    id: "friday-fc",
    name: "Friday FC",
    logo: null,
    sport: "Football",
    location: "CMC, Addis Ababa",
    activeMembers: 9,
    capacity: 16,
    role: "MEMBER",
  },
  {
    id: "hoops-collective",
    name: "Hoops Collective",
    logo: null,
    sport: "Basketball",
    location: "Sarbet, Addis Ababa",
    activeMembers: 8,
    capacity: 12,
    role: "ADMIN",
  },
];

export const mockMatches: UpcomingMatch[] = [
  {
    id: "m1",
    sport: "Football",
    opponentLabel: "vs Friday FC",
    pitchName: "Bole Arena",
    date: "2026-08-14",
    time: "18:00",
    status: "confirmed",
  },
  {
    id: "m2",
    sport: "Football",
    opponentLabel: "Open match — 3 spots left",
    pitchName: "CMC Pitch 2",
    date: "2026-08-16",
    time: "16:30",
    status: "open",
  },
  {
    id: "m3",
    sport: "Basketball",
    opponentLabel: "vs Court Kings",
    pitchName: "Sarbet Indoor Court",
    date: "2026-08-17",
    time: "19:00",
    status: "pending_payment",
  },
];

export const mockTournaments: TournamentPreview[] = [
  {
    id: "t1",
    name: "Bole Weekend Cup",
    sport: "Football",
    location: "Bole, Addis Ababa",
    status: "registration_open",
    startDate: "2026-08-22",
    teamsJoined: 6,
    teamsMax: 8,
  },
  {
    id: "t2",
    name: "CMC 3x3 Showdown",
    sport: "Basketball",
    location: "CMC, Addis Ababa",
    status: "upcoming",
    startDate: "2026-09-02",
    teamsJoined: 10,
    teamsMax: 16,
  },
];

export const mockNotifications: AppNotification[] = [
  {
    id: "n1",
    category: "team",
    title: "Team invitation",
    message: "Friday FC invited you to join as a member.",
    time: "12m ago",
    read: false,
    action: {
      label: "Respond",
      kind: "accept_decline",
    },
  },
  {
    id: "n2",
    category: "match",
    title: "Match reminder",
    message: "Bole United vs Friday FC starts in 3 hours.",
    time: "1h ago",
    read: false,
    action: {
      label: "View match",
      kind: "open",
      to: "/matches/m1",
    },
  },
  {
    id: "n3",
    category: "booking",
    title: "Payment update",
    message: "3 of 10 shares paid for Saturday's booking — 06:42 remaining.",
    time: "2h ago",
    read: false,
    action: {
      label: "View booking",
      kind: "open",
      to: "/matches/m3",
    },
  },
  {
    id: "n4",
    category: "tournament",
    title: "Registration deadline",
    message: "Bole Weekend Cup registration closes in 2 days.",
    time: "5h ago",
    read: true,
    action: {
      label: "View tournament",
      kind: "open",
      to: "/discover/tournaments/t1",
    },
  },
  {
    id: "n5",
    category: "team",
    title: "Join request approved",
    message: "You're now a member of Hoops Collective.",
    time: "1d ago",
    read: true,
  },
];

// ---------------------------------------------------------
// Task 3/4/5 mock data
// TODO: replace with real API calls
// ---------------------------------------------------------

export const mockAllMatches: MatchFull[] = [
  {
    id: "m1",
    sport: "Football",
    opponentLabel: "vs Friday FC",
    teamName: "Bole United",
    pitchName: "Bole Arena",
    pitchAddress: "Bole Rd, Addis Ababa",
    date: "2026-08-14",
    time: "18:00",
    durationMinutes: 90,
    stage: "upcoming",
    bookingStatus: "confirmed",
    totalPriceEtb: 1000,
    paidEtb: 1000,
    shareCount: 10,
    sharePaidCount: 10,
  },
  {
    id: "m2",
    sport: "Football",
    opponentLabel: "Open match — 3 spots left",
    teamName: "Bole United",
    pitchName: "CMC Pitch 2",
    pitchAddress: "CMC, Addis Ababa",
    date: "2026-08-16",
    time: "16:30",
    durationMinutes: 90,
    stage: "upcoming",
    bookingStatus: "open",
    totalPriceEtb: 900,
    paidEtb: 630,
    shareCount: 9,
    sharePaidCount: 7,
  },
  {
    id: "m3",
    sport: "Basketball",
    opponentLabel: "vs Court Kings",
    teamName: "Hoops Collective",
    pitchName: "Sarbet Indoor Court",
    pitchAddress: "Sarbet, Addis Ababa",
    date: "2026-08-17",
    time: "19:00",
    durationMinutes: 60,
    stage: "upcoming",
    bookingStatus: "pending_payment",
    totalPriceEtb: 800,
    paidEtb: 240,
    shareCount: 8,
    sharePaidCount: 3,
  },
  {
    id: "m4",
    sport: "Football",
    opponentLabel: "vs CMC Rangers",
    teamName: "Bole United",
    pitchName: "Bole Arena",
    pitchAddress: "Bole Rd, Addis Ababa",
    date: "2026-08-12",
    time: "17:00",
    durationMinutes: 90,
    stage: "ongoing",
    bookingStatus: "confirmed",
    totalPriceEtb: 1000,
    paidEtb: 1000,
    shareCount: 10,
    sharePaidCount: 10,
  },
  {
    id: "m5",
    sport: "Football",
    opponentLabel: "vs Sarbet FC",
    teamName: "Bole United",
    pitchName: "Bole Arena",
    pitchAddress: "Bole Rd, Addis Ababa",
    date: "2026-08-01",
    time: "18:00",
    durationMinutes: 90,
    stage: "completed",
    bookingStatus: "confirmed",
    totalPriceEtb: 1000,
    paidEtb: 1000,
    shareCount: 10,
    sharePaidCount: 10,
    result: {
      teamScore: 3,
      opponentScore: 1,
    },
  },
  {
    id: "m6",
    sport: "Basketball",
    opponentLabel: "vs Street Ballers",
    teamName: "Hoops Collective",
    pitchName: "Sarbet Indoor Court",
    pitchAddress: "Sarbet, Addis Ababa",
    date: "2026-07-28",
    time: "19:00",
    durationMinutes: 60,
    stage: "completed",
    bookingStatus: "confirmed",
    totalPriceEtb: 800,
    paidEtb: 800,
    shareCount: 8,
    sharePaidCount: 8,
    result: {
      teamScore: 54,
      opponentScore: 61,
    },
  },
];

export const mockPitches: PitchResult[] = [
  {
    id: "p1",
    name: "Bole Arena",
    location: "Bole, Addis Ababa",
    sport: ["Football"],
    pricePerHourEtb: 700,
    rating: 4.8,
    nextAvailable: "Today 6:00 PM",
  },
  {
    id: "p2",
    name: "CMC Pitch 2",
    location: "CMC, Addis Ababa",
    sport: ["Football"],
    pricePerHourEtb: 550,
    rating: 4.5,
    nextAvailable: "Today 4:30 PM",
  },
  {
    id: "p3",
    name: "Sarbet Indoor Court",
    location: "Sarbet, Addis Ababa",
    sport: ["Basketball"],
    pricePerHourEtb: 800,
    rating: 4.7,
    nextAvailable: "Tomorrow 9:00 AM",
  },
  {
    id: "p4",
    name: "Summit Turf",
    location: "Summit, Addis Ababa",
    sport: ["Football"],
    pricePerHourEtb: 650,
    rating: 4.3,
    nextAvailable: "Today 8:00 PM",
  },
];

export const mockPublicTeams: PublicTeamResult[] = [
  {
    id: "friday-fc",
    name: "Friday FC",
    logo: null,
    sport: "Football",
    location: "CMC, Addis Ababa",
    activeMembers: 9,
    capacity: 16,
    skillLevel: "Intermediate",
    visibility: "public",
  },
  {
    id: "atlas-fc",
    name: "Atlas FC",
    logo: null,
    sport: "Football",
    location: "Gerji, Addis Ababa",
    activeMembers: 15,
    capacity: 20,
    skillLevel: "Advanced",
    visibility: "request",
  },
  {
    id: "night-owls",
    name: "Night Owls Basketball",
    logo: null,
    sport: "Basketball",
    location: "Sarbet, Addis Ababa",
    activeMembers: 6,
    capacity: 12,
    skillLevel: "Beginner",
    visibility: "public",
  },
];

export const mockAllTournaments: TournamentFull[] = [
  {
    id: "t1",
    name: "Bole Weekend Cup",
    sport: "Football",
    location: "Bole, Addis Ababa",
    organizer: "Bole United",
    status: "registration_open",
    registrationDeadline: "2026-08-19",
    startDate: "2026-08-22",
    teamsJoined: 6,
    teamsMax: 8,
    entryFeeEtb: 500,
    description:
      "Weekend knockout cup, winner takes the trophy and bragging rights.",
  },
  {
    id: "t2",
    name: "CMC 3x3 Showdown",
    sport: "Basketball",
    location: "CMC, Addis Ababa",
    organizer: "Hoops Collective",
    status: "upcoming",
    registrationDeadline: "2026-08-25",
    startDate: "2026-09-02",
    teamsJoined: 10,
    teamsMax: 16,
    entryFeeEtb: 300,
    description:
      "Fast-paced 3x3 tournament, round robin then knockout.",
  },
  {
    id: "t3",
    name: "Summit Summer League",
    sport: "Football",
    location: "Summit, Addis Ababa",
    organizer: "Summit Turf",
    status: "ongoing",
    registrationDeadline: "2026-07-20",
    startDate: "2026-07-25",
    teamsJoined: 8,
    teamsMax: 8,
    entryFeeEtb: 400,
    description:
      "Ongoing round robin league running through August.",
  },
  {
    id: "t4",
    name: "Sarbet Spring Cup",
    sport: "Basketball",
    location: "Sarbet, Addis Ababa",
    organizer: "Sarbet Indoor Court",
    status: "completed",
    registrationDeadline: "2026-04-01",
    startDate: "2026-04-10",
    teamsJoined: 12,
    teamsMax: 12,
    entryFeeEtb: 250,
    description:
      "Completed — congrats to this season's winners.",
  },
];

// Keep the original name so existing imports using mockProfile
// continue to work.
export const mockProfile: UserProfile = {
  fullName: "Yonas Tesfaye",
  phone: "+251 91 234 5678",
  email: "yonas.tesfaye@example.com",
  photo: null,
};

// Alias for any components that were changed to use mockUserProfile.
export const mockUserProfile = mockProfile;

