# Generated by Django 6.0.3 on 2026-08-13 07:58

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(editable=False, max_length=140, unique=True)),
                ('sport', models.CharField(choices=[('football', 'Football')], default='football', max_length=20)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', help_text='PUBLIC teams appear in discovery and accept join requests.', max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('suspended', 'Suspended')], default='active', help_text='ARCHIVED = owner retired the team. SUSPENDED = platform action.', max_length=10)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='teams/logos/')),
                ('description', models.TextField(blank=True, max_length=220)),
                ('area', models.CharField(blank=True, help_text="Neighbourhood / sub-city, e.g. 'Bole'.", max_length=100)),
                ('city', models.CharField(blank=True, default='Addis Ababa', max_length=100)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('skill_level', models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('professional', 'Professional')], max_length=20)),
                ('age_category', models.CharField(blank=True, choices=[('open', 'Open'), ('u18', 'Under 18'), ('u21', 'Under 21'), ('adult', 'Adult'), ('other', 'Other')], default='open', max_length=10)),
                ('preferred_days', models.JSONField(blank=True, default=list, help_text="List of day codes, e.g. ['mon', 'wed', 'sat']. Not queried at scale, so JSON is fine here — same rationale as `preferences`.")),
                ('play_time', models.CharField(blank=True, choices=[('morning', 'Morning (6–11)'), ('afternoon', 'Afternoon (11–5)'), ('evening', 'Evening (5–10)')], max_length=20)),
                ('max_roster_size', models.PositiveSmallIntegerField(default=25, help_text='Maximum number of ACTIVE members allowed on this team.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)])),
                ('preferences', models.JSONField(blank=True, default=dict)),
                ('version', models.PositiveIntegerField(default=0)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='Audit trail of who originally created the team. NOT the current owner — ownership can be transferred and always lives on TeamMembership.', on_delete=django.db.models.deletion.PROTECT, related_name='teams_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
                'db_table': 'teams_team',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeamInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invitation_type', models.CharField(choices=[('direct', 'Direct (searched user)'), ('link', 'Shareable link / QR'), ('code', 'Short join code')], max_length=10)),
                ('token', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('code', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='pending', max_length=10)),
                ('max_uses', models.PositiveIntegerField(blank=True, null=True)),
                ('redemption_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_invitations_sent', to=settings.AUTH_USER_MODEL)),
                ('invited_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_invitations_received', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='team.team')),
            ],
            options={
                'verbose_name': 'Team Invitation',
                'verbose_name_plural': 'Team Invitations',
                'db_table': 'teams_teaminvitation',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeamInvitationRedemption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('redeemed_at', models.DateTimeField(auto_now_add=True)),
                ('invitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='team.teaminvitation')),
                ('redeemed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_invitation_redemptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Team Invitation Redemption',
                'verbose_name_plural': 'Team Invitation Redemptions',
                'db_table': 'teams_teaminvitationredemption',
                'ordering': ['-redeemed_at'],
            },
        ),
        migrations.CreateModel(
            name='TeamJoinRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=0)),
                ('reviewed_by', models.ForeignKey(blank=True, help_text="Nullable via SET_NULL: if the reviewing admin's account is later deleted, the historical review (status, reviewed_at) must survive — only the 'who' is lost.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_join_requests_reviewed', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='team.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_join_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Team Join Request',
                'verbose_name_plural': 'Team Join Requests',
                'db_table': 'teams_teamjoinrequest',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeamMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('member', 'Member')], default='member', max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('left', 'Left'), ('removed', 'Removed')], default='active', max_length=10)),
                ('source', models.CharField(choices=[('team_creation', 'Created the team'), ('direct_invitation', 'Accepted a direct invitation'), ('link_invitation', 'Accepted a link invitation'), ('code_invitation', 'Accepted a code invitation'), ('join_request', 'Approved public join request'), ('ownership_transfer', 'Became owner via transfer')], default='team_creation', max_length=20)),
                ('jersey_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('preferred_position', models.CharField(blank=True, choices=[('gk', 'Goalkeeper'), ('def', 'Defender'), ('mid', 'Midfielder'), ('fwd', 'Forward')], max_length=3)),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status_changed_at', models.DateTimeField(blank=True, null=True)),
                ('last_active_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='team.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Team Membership',
                'verbose_name_plural': 'Team Memberships',
                'db_table': 'teams_teammembership',
                'ordering': ['-joined_at'],
            },
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['visibility', 'status'], name='teams_team_visibil_c680ea_idx'),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['sport'], name='teams_team_sport_727ab2_idx'),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['city', 'area'], name='teams_team_city_c45001_idx'),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['deleted_at'], name='teams_team_deleted_79b14a_idx'),
        ),
        migrations.AddConstraint(
            model_name='team',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), condition=models.Q(('deleted_at__isnull', True)), name='uniq_team_name_ci_not_deleted'),
        ),
        migrations.AddConstraint(
            model_name='team',
            constraint=models.CheckConstraint(condition=models.Q(('max_roster_size__gte', 1), ('max_roster_size__lte', 50)), name='team_max_roster_size_within_bounds'),
        ),
        migrations.AddIndex(
            model_name='teaminvitation',
            index=models.Index(fields=['token'], name='teams_teami_token_e4e861_idx'),
        ),
        migrations.AddIndex(
            model_name='teaminvitation',
            index=models.Index(fields=['code'], name='teams_teami_code_b2c272_idx'),
        ),
        migrations.AddIndex(
            model_name='teaminvitation',
            index=models.Index(fields=['team', 'status'], name='teams_teami_team_id_02e3eb_idx'),
        ),
        migrations.AddIndex(
            model_name='teaminvitation',
            index=models.Index(fields=['invited_user', 'status'], name='teams_teami_invited_9c17c1_idx'),
        ),
        migrations.AddIndex(
            model_name='teaminvitation',
            index=models.Index(fields=['status', 'expires_at'], name='teams_teami_status_61cc73_idx'),
        ),
        migrations.AddConstraint(
            model_name='teaminvitation',
            constraint=models.UniqueConstraint(condition=models.Q(('invitation_type', 'direct'), ('status', 'pending')), fields=('team', 'invited_user'), name='uniq_pending_direct_invite_per_team_user'),
        ),
        migrations.AddConstraint(
            model_name='teaminvitation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('code__isnull', True), ('invitation_type', 'direct'), ('invited_user__isnull', False), ('token__isnull', True)), models.Q(('code__isnull', True), ('invitation_type', 'link'), ('invited_user__isnull', True), ('token__isnull', False)), models.Q(('code__isnull', False), ('invitation_type', 'code'), ('invited_user__isnull', True), ('token__isnull', True)), _connector='OR'), name='invitation_fields_match_type'),
        ),
        migrations.AddConstraint(
            model_name='teaminvitation',
            constraint=models.CheckConstraint(condition=models.Q(('max_uses__isnull', True), ('max_uses__gte', 1), _connector='OR'), name='invitation_max_uses_positive_or_unlimited'),
        ),
        migrations.AddConstraint(
            model_name='teaminvitation',
            constraint=models.CheckConstraint(condition=models.Q(('max_uses__isnull', True), ('redemption_count__lte', models.F('max_uses')), _connector='OR'), name='invitation_redemption_count_within_max_uses'),
        ),
        migrations.AddIndex(
            model_name='teaminvitationredemption',
            index=models.Index(fields=['invitation'], name='teams_teami_invitat_980267_idx'),
        ),
        migrations.AddIndex(
            model_name='teaminvitationredemption',
            index=models.Index(fields=['redeemed_by'], name='teams_teami_redeeme_dc7f4a_idx'),
        ),
        migrations.AddConstraint(
            model_name='teaminvitationredemption',
            constraint=models.UniqueConstraint(fields=('invitation', 'redeemed_by'), name='uniq_redemption_per_invitation_user'),
        ),
        migrations.AddIndex(
            model_name='teamjoinrequest',
            index=models.Index(fields=['team', 'status'], name='teams_teamj_team_id_c0168d_idx'),
        ),
        migrations.AddIndex(
            model_name='teamjoinrequest',
            index=models.Index(fields=['user', 'status'], name='teams_teamj_user_id_b7e711_idx'),
        ),
        migrations.AddConstraint(
            model_name='teamjoinrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('team', 'user'), name='uniq_pending_join_request_per_team_user'),
        ),
        migrations.AddConstraint(
            model_name='teamjoinrequest',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('reviewed_at__isnull', True), ('status', 'pending')), models.Q(models.Q(('status', 'pending'), _negated=True), ('reviewed_at__isnull', False)), _connector='OR'), name='join_request_reviewed_at_matches_status'),
        ),
        migrations.AddIndex(
            model_name='teammembership',
            index=models.Index(fields=['team', 'status'], name='teams_teamm_team_id_11426a_idx'),
        ),
        migrations.AddIndex(
            model_name='teammembership',
            index=models.Index(fields=['user', 'status'], name='teams_teamm_user_id_e0b78b_idx'),
        ),
        migrations.AddIndex(
            model_name='teammembership',
            index=models.Index(fields=['team', 'source'], name='teams_teamm_team_id_1ee593_idx'),
        ),
        migrations.AddConstraint(
            model_name='teammembership',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('team', 'user'), name='uniq_active_membership_per_team_user'),
        ),
        migrations.AddConstraint(
            model_name='teammembership',
            constraint=models.UniqueConstraint(condition=models.Q(('role', 'owner'), ('status', 'active')), fields=('team',), name='uniq_active_owner_per_team'),
        ),
        migrations.AddConstraint(
            model_name='teammembership',
            constraint=models.UniqueConstraint(condition=models.Q(('jersey_number__isnull', False), ('status', 'active')), fields=('team', 'jersey_number'), name='uniq_active_jersey_number_per_team'),
        ),
        migrations.AddConstraint(
            model_name='teammembership',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('role', 'owner'), _negated=True), ('status', 'active'), _connector='OR'), name='owner_membership_must_be_active'),
        ),
    ]
