# Generated by Django 6.0.3 on 2026-09-30 07:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0005_slot_manual_close_reason'),
        ('team_booking', '0005_teambookingrequest_booked_popup_shown'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PitchOwnerBankAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bank', models.CharField(choices=[('cbe', 'Commercial Bank of Ethiopia'), ('boa', 'Bank of Abyssinia'), ('telebirr', 'Telebirr'), ('mpesa', 'M-Pesa'), ('cbebirr', 'CBE Birr'), ('dashen', 'Dashen Bank'), ('awash', 'Awash Bank'), ('siinqee', 'Siinqee Bank'), ('kaafiebirr', 'Kaafi eBirr'), ('zemen', 'Zemen Bank')], max_length=15)),
                ('account_holder_name', models.CharField(max_length=150)),
                ('account_number', models.CharField(blank=True, max_length=30)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payment_owner_bank_account',
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_expected', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_mode', models.CharField(choices=[('not_configured', 'Not Configured'), ('gateway', 'Automated Gateway'), ('manual_bank', 'Manual Bank Transfer')], max_length=15)),
                ('gateway_provider', models.CharField(blank=True, choices=[('chapa', 'Chapa'), ('santimpay', 'SantimPay'), ('arifpay', 'ArifPay')], max_length=15)),
                ('gateway_reference', models.CharField(blank=True, max_length=100)),
                ('bank', models.CharField(blank=True, choices=[('cbe', 'Commercial Bank of Ethiopia'), ('boa', 'Bank of Abyssinia'), ('telebirr', 'Telebirr'), ('mpesa', 'M-Pesa'), ('cbebirr', 'CBE Birr'), ('dashen', 'Dashen Bank'), ('awash', 'Awash Bank'), ('siinqee', 'Siinqee Bank'), ('kaafiebirr', 'Kaafi eBirr'), ('zemen', 'Zemen Bank')], max_length=15)),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='payment_screenshots/%Y/%m/')),
                ('reference_number', models.CharField(blank=True, max_length=64)),
                ('account_suffix', models.CharField(blank=True, max_length=10)),
                ('payer_phone_number', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('needs_review', 'Needs Manual Review'), ('expired', 'Expired')], default='pending', max_length=15)),
                ('verify_request_id', models.CharField(blank=True, max_length=100)),
                ('verify_response', models.JSONField(blank=True, null=True)),
                ('verified_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('verified_transaction_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.CharField(blank=True, max_length=100)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to='bookings.booking')),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to=settings.AUTH_USER_MODEL)),
                ('pitch_owner', models.ForeignKey(help_text='Snapshotted from booking.pitch.owner at creation time.', on_delete=django.db.models.deletion.CASCADE, related_name='received_payment_transactions', to=settings.AUTH_USER_MODEL)),
                ('team_booking_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to='team_booking.teambookingpayment')),
                ('owner_bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_transactions', to='payment.pitchownerbankaccount')),
            ],
            options={
                'db_table': 'payment_transaction',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='PitchOwnerPaymentProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_mode', models.CharField(choices=[('not_configured', 'Not Configured'), ('gateway', 'Automated Gateway'), ('manual_bank', 'Manual Bank Transfer')], default='not_configured', max_length=15)),
                ('gateway_provider', models.CharField(blank=True, choices=[('chapa', 'Chapa'), ('santimpay', 'SantimPay'), ('arifpay', 'ArifPay')], max_length=15)),
                ('gateway_merchant_ref', models.CharField(blank=True, max_length=100)),
                ('configured_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('configured_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_profiles_configured', to=settings.AUTH_USER_MODEL)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payment_owner_profile',
            },
        ),
        migrations.AddConstraint(
            model_name='pitchownerbankaccount',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('owner', 'bank'), name='uniq_active_bank_per_owner_per_bank_type'),
        ),
        migrations.AddConstraint(
            model_name='pitchownerbankaccount',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('bank__in', ['mpesa', 'cbebirr', 'telebirr']), ('phone_number__gt', '')), models.Q(models.Q(('bank__in', ['mpesa', 'cbebirr', 'telebirr']), _negated=True), ('account_number__gt', '')), _connector='OR'), name='bank_account_has_required_identifier'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['bank', 'reference_number'], name='payment_tra_bank_cdebec_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['booking', 'status'], name='payment_tra_booking_c47f32_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['payer', 'status'], name='payment_tra_payer_i_3611ad_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['status', 'submitted_at'], name='payment_tra_status_4f4216_idx'),
        ),
        migrations.AddConstraint(
            model_name='paymenttransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'verified'), models.Q(('reference_number', ''), _negated=True)), fields=('bank', 'reference_number'), name='uniq_verified_reference_per_bank'),
        ),
        migrations.AddConstraint(
            model_name='paymenttransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'processing']), models.Q(('reference_number', ''), _negated=True)), fields=('bank', 'reference_number'), name='uniq_inflight_reference_per_bank'),
        ),
        migrations.AddConstraint(
            model_name='paymenttransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('booking__isnull', False), ('status', 'verified')), fields=('booking',), name='uniq_verified_payment_per_booking'),
        ),
        migrations.AddConstraint(
            model_name='paymenttransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'verified'), ('team_booking_payment__isnull', False)), fields=('team_booking_payment',), name='uniq_verified_payment_per_team_booking_payment'),
        ),
        migrations.AddConstraint(
            model_name='paymenttransaction',
            constraint=models.CheckConstraint(condition=models.Q(('amount_expected__gt', 0)), name='payment_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='paymenttransaction',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('booking__isnull', False), ('team_booking_payment__isnull', True)), models.Q(('booking__isnull', True), ('team_booking_payment__isnull', False)), _connector='OR'), name='payment_target_exactly_one'),
        ),
        migrations.AddConstraint(
            model_name='pitchownerpaymentprofile',
            constraint=models.CheckConstraint(condition=models.Q(('payment_mode', 'not_configured'), ('payment_mode', 'manual_bank'), models.Q(('gateway_provider__gt', ''), ('payment_mode', 'gateway')), _connector='OR'), name='payment_profile_gateway_requires_provider'),
        ),
    ]
