# Generated by Django 6.0.3 on 2026-10-04 08:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_remove_solobookinghold_bookings_so_player__86a627_idx_and_more'),
        ('payment', '0002_remove_paymenttransaction_payment_target_exactly_one_and_more'),
        ('team_booking', '0005_teambookingrequest_booked_popup_shown'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='paymenttransaction',
            name='uniq_verified_payment_per_solo_hold',
        ),
        migrations.RemoveConstraint(
            model_name='pitchownerbankaccount',
            name='bank_account_has_required_identifier',
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='team_booking_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to='team_booking.teambookingpayment'),
        ),
        migrations.AddConstraint(
            model_name='paymenttransaction',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('booking__isnull', False), ('team_booking_payment__isnull', True)), models.Q(('booking__isnull', True), ('team_booking_payment__isnull', False)), _connector='OR'), name='payment_target_exactly_one'),
        ),
        migrations.AddConstraint(
            model_name='pitchownerbankaccount',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('bank__in', ['cbebirr', 'telebirr', 'mpesa']), ('phone_number__gt', '')), models.Q(models.Q(('bank__in', ['cbebirr', 'telebirr', 'mpesa']), _negated=True), ('account_number__gt', '')), _connector='OR'), name='bank_account_has_required_identifier'),
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='solo_booking_hold',
        ),
    ]
