# Generated by Django 6.0.3 on 2026-10-04 08:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_remove_paymenttransaction_payment_target_exactly_one_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='pitchownerbankaccount',
            name='bank_account_has_required_identifier',
        ),
        migrations.AddConstraint(
            model_name='pitchownerbankaccount',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('bank__in', ['mpesa', 'telebirr', 'cbebirr']), ('phone_number__gt', '')), models.Q(models.Q(('bank__in', ['mpesa', 'telebirr', 'cbebirr']), _negated=True), ('account_number__gt', '')), _connector='OR'), name='bank_account_has_required_identifier'),
        ),
    ]
