# Generated by Django 6.0.3 on 2026-10-04 08:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_solobookinghold'),
        ('payment', '0004_remove_pitchownerbankaccount_bank_account_has_required_identifier_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='paymenttransaction',
            name='payment_target_exactly_one',
        ),
        migrations.RemoveConstraint(
            model_name='pitchownerbankaccount',
            name='bank_account_has_required_identifier',
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='solo_booking_hold',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to='bookings.solobookinghold'),
        ),
        migrations.AddConstraint(
            model_name='paymenttransaction',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('booking__isnull', False), ('solo_booking_hold__isnull', True), ('team_booking_payment__isnull', True)), models.Q(('booking__isnull', True), ('solo_booking_hold__isnull', True), ('team_booking_payment__isnull', False)), models.Q(('booking__isnull', True), ('solo_booking_hold__isnull', False), ('team_booking_payment__isnull', True)), _connector='OR'), name='payment_target_exactly_one'),
        ),
        migrations.AddConstraint(
            model_name='paymenttransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('solo_booking_hold__isnull', False), ('status', 'verified')), fields=('solo_booking_hold',), name='uniq_verified_payment_per_solo_hold'),
        ),
        migrations.AddConstraint(
            model_name='pitchownerbankaccount',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('bank__in', ['telebirr', 'mpesa', 'cbebirr']), ('phone_number__gt', '')), models.Q(models.Q(('bank__in', ['telebirr', 'mpesa', 'cbebirr']), _negated=True), ('account_number__gt', '')), _connector='OR'), name='bank_account_has_required_identifier'),
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='team_booking_payment',
        ),
    ]
