# Generated by Django 6.0.3 on 2026-10-04 14:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_remove_pitchownerbankaccount_bank_account_has_required_identifier_and_more'),
        ('team_booking', '0005_teambookingrequest_booked_popup_shown'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='pitchownerbankaccount',
            name='bank_account_has_required_identifier',
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='team_booking_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to='team_booking.teambookingpayment'),
        ),
        migrations.AddConstraint(
            model_name='pitchownerbankaccount',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('bank__in', ['telebirr', 'cbebirr', 'mpesa']), ('phone_number__gt', '')), models.Q(models.Q(('bank__in', ['telebirr', 'cbebirr', 'mpesa']), _negated=True), ('account_number__gt', '')), _connector='OR'), name='bank_account_has_required_identifier'),
        ),
    ]
