# Generated by Django 6.0.3 on 2026-10-06 10:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_remove_pitchownerbankaccount_bank_account_has_required_identifier_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='pitchownerbankaccount',
            name='bank_account_has_required_identifier',
        ),
        migrations.AddConstraint(
            model_name='pitchownerbankaccount',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('bank__in', ['cbebirr', 'mpesa', 'telebirr']), ('phone_number__gt', '')), models.Q(models.Q(('bank__in', ['cbebirr', 'mpesa', 'telebirr']), _negated=True), ('account_number__gt', '')), _connector='OR'), name='bank_account_has_required_identifier'),
        ),
    ]
