# Generated by Django 6.0.3 on 2026-10-07 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0009_remove_pitchownerbankaccount_bank_account_has_required_identifier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='completion_acknowledged',
            field=models.BooleanField(default=False),
        ),
    ]
